### ISSUE TITLE
make an arduino library and add it to the library manager

### ISSUE THREAD

**Issue by gschora** [Involt/Involt#114]
This is an awesome project! Finally I can make a quick gui for a prototype!

It would be great if this was a library and manageble through the arduino library manager.

**Comment by ErniW** [comment]
Thanks,

Yes, it was considered and definitely should be put in backlog. There are few things to consider:

- I could pack the existing involt-basic sketch into a library but there are users who (for example) add additional pins to `involtReceive` function or other things there. I don't know how to handle these changes within library for end-user.
- It makes sense if I make more sketches for future communication methods. It will be easier to maintain.
- Does the existing sketch has readability issues? At current version, there is no need of adding additional step to make Involt work. (downloading and installing library).
- Finally, it would be great if Involt as library would be put directly into Arduino IDE/library manager without external download. How to achieve that?

**Comment by gschora** [comment]
The main reason for me to have a library is to remove code from the main file.

- I'm not a really good programmer, but you could do all the setup in the constructor. Maybe an approach like in the library serialcommand where you define the functions on different commands in the setup funktion would work. If I have time I will look into it.
- You can write different definitions for different plattforms, e.g. when you use an esp it automatically knows to not use serial but http-requests.
- No, the sketch is easy to read.
- I found this link, where they describe how to make a library for the manager: [https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ](url)
